openapi: 3.0.0
info:
    version: 1.0.0
    title: Tomme API
servers:
    - url: 'https://tomme.balnis.eu/v1'
paths:
    /create-connection:
        summary: Initiates connection between Papet client and Tomme client
        get:
            operationId: create-connection
            parameters:
                -   name: connectionId
                    in: query
                    required: true
                    schema:
                        type: string
                -   name: cpmClientName
                    in: query
                    required: true
                    schema:
                        type: string
                -   name: nonce
                    in: query
                    required: true
                    schema:
                        type: string

      responses:
        '200':
            content:
                text/html:
                    schema:
                        type: string
        default:
          description: Unexpected error
